// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnZCclBtvYG7JQfRTAf2gp0M8fGotYjFQ',
    appId: '1:98490696242:web:213a4d61d588e1ef5e722b',
    messagingSenderId: '98490696242',
    projectId: 'programmics-cee09',
    authDomain: 'programmics-cee09.firebaseapp.com',
    storageBucket: 'programmics-cee09.appspot.com',
    measurementId: 'G-QJFRCJXXG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8bKBna4dgXjJBXSojgN6AnJQ76GPlVNo',
    appId: '1:98490696242:android:537cc0e92885c41a5e722b',
    messagingSenderId: '98490696242',
    projectId: 'programmics-cee09',
    storageBucket: 'programmics-cee09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1nOCa0a57TI7KYXD_4jAXyoTRONFVcmg',
    appId: '1:98490696242:ios:df43de5a158556f05e722b',
    messagingSenderId: '98490696242',
    projectId: 'programmics-cee09',
    storageBucket: 'programmics-cee09.appspot.com',
    androidClientId: '98490696242-dc31mclmp149k2rg9hhkpu2gveu4f0k8.apps.googleusercontent.com',
    iosClientId: '98490696242-caeppd8uobqmaisdel15pf44vcgv3jb6.apps.googleusercontent.com',
    iosBundleId: 'dev.flutterexplained.webrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1nOCa0a57TI7KYXD_4jAXyoTRONFVcmg',
    appId: '1:98490696242:ios:033ab76e8ee860f55e722b',
    messagingSenderId: '98490696242',
    projectId: 'programmics-cee09',
    storageBucket: 'programmics-cee09.appspot.com',
    androidClientId: '98490696242-dc31mclmp149k2rg9hhkpu2gveu4f0k8.apps.googleusercontent.com',
    iosClientId: '98490696242-cca8rtdfkj4lncsrh6ra83u0ues5ikgn.apps.googleusercontent.com',
    iosBundleId: 'dev.flutterexplained.webrtcTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnZCclBtvYG7JQfRTAf2gp0M8fGotYjFQ',
    appId: '1:98490696242:web:98b634709ea1e1b75e722b',
    messagingSenderId: '98490696242',
    projectId: 'programmics-cee09',
    authDomain: 'programmics-cee09.firebaseapp.com',
    storageBucket: 'programmics-cee09.appspot.com',
    measurementId: 'G-REKY75D3TL',
  );
}
